from __future__ import annotations

import json
import os
import shlex
from dataclasses import dataclass
from pathlib import Path

from .planner import PlanResult


@dataclass
class DeployResult:
    out_dir: str
    files: list[str]
    dry_run: bool
    warnings: list[str]

    def to_dict(self) -> dict[str, object]:
        return {"out_dir": self.out_dir, "files": self.files, "dry_run": self.dry_run, "warnings": self.warnings}


def _write_executable(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8")
    path.chmod(path.stat().st_mode | 0o111)


def _backend_check(backend: str) -> list[str]:
    if backend == "mlx":
        return [
            'python -c "import importlib.util, sys; sys.exit(0 if importlib.util.find_spec(\'mlx_lm\') else 1)"',
        ]
    if backend == "ollama":
        return ['command -v ollama >/dev/null 2>&1']
    if backend == "vllm":
        return ['command -v vllm >/dev/null 2>&1']
    return ['command -v llama-cli >/dev/null 2>&1 || command -v llama-server >/dev/null 2>&1']


def _preflight_script(plan: PlanResult, model_path: str) -> str:
    backend = plan.recommended_backend
    check_lines = _backend_check(backend)
    severe = plan.verdict in {"does-not-fit", "not-recommended"} or plan.risk_level in {"high", "extreme"}
    default_model = shlex.quote(model_path)
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            "",
            "# Local-only preflight generated by local-llm-lab.",
            "# It does not download models or start a server.",
            f"DEFAULT_MODEL={default_model}",
            'MODEL="${MODEL:-$DEFAULT_MODEL}"',
            f"BACKEND={shlex.quote(backend)}",
            f"VERDICT={shlex.quote(plan.verdict)}",
            f"RISK={shlex.quote(plan.risk_level)}",
            f"RUNTIME_GIB={plan.memory.runtime_required_gib}",
            f"MARGIN_GIB={plan.memory.margin_gib}",
            f"DISK_AVAILABLE_GIB={plan.inputs.hardware.disk_available_gib}",
            "errors=0",
            "",
            'echo "local-llm-lab preflight"',
            'echo "backend=$BACKEND verdict=$VERDICT risk=$RISK runtime=${RUNTIME_GIB}GiB margin=${MARGIN_GIB}GiB"',
            'echo "model=$MODEL"',
            "",
            "if [ ! -e \"$MODEL\" ]; then",
            '  echo "ERROR: model path does not exist. Set MODEL=/path/to/weights before running."',
            "  errors=$((errors + 1))",
            "fi",
            "",
            f"if {' '.join(check_lines)}; then",
            '  echo "backend check: ok"',
            "else",
            '  echo "ERROR: recommended backend binary/library was not found for $BACKEND."',
            "  errors=$((errors + 1))",
            "fi",
            "",
            "if [ \"$DISK_AVAILABLE_GIB\" != \"None\" ]; then",
            '  echo "disk available: ${DISK_AVAILABLE_GIB}GiB"',
            "fi",
            "",
            "if [ \"$VERDICT\" = \"does-not-fit\" ] || [ \"$VERDICT\" = \"not-recommended\" ] || [ \"$RISK\" = \"high\" ] || [ \"$RISK\" = \"extreme\" ]; then",
            '  echo "WARNING: this plan is high risk. Prefer a lower quantization, shorter context, or different hardware before a real launch."',
            f"  {'errors=$((errors + 1))' if severe else ':'}",
            "fi",
            "",
            "if [ \"$errors\" -gt 0 ]; then",
            '  echo "preflight failed with $errors issue(s)."',
            "  exit 1",
            "fi",
            "",
            'echo "preflight passed. You can now inspect the generated run scripts."',
            "",
        ]
    )


def _runbook(plan: PlanResult, model_path: str) -> str:
    warnings = "\n".join(f"- {item}" for item in plan.warnings) or "- None"
    downgrades = "\n".join(f"- {item}" for item in plan.downgrade_options) or "- None"
    return "\n".join(
        [
            "# local-llm-lab Deploy Runbook",
            "",
            "This directory is a dry-run deployment bundle. It does not download model weights.",
            "",
            "## Decision",
            "",
            f"- Model: `{plan.inputs.model.id}`",
            f"- Backend: `{plan.recommended_backend}`",
            f"- Quantization: `{plan.inputs.quant.name}`",
            f"- Context: `{plan.inputs.context_tokens}` tokens",
            f"- Verdict: **{plan.verdict}**",
            f"- Risk: **{plan.risk_level}**",
            f"- Runtime required: `{plan.memory.runtime_required_gib} GiB`",
            f"- Available runtime memory: `{plan.memory.available_runtime_gib} GiB`",
            f"- Margin: `{plan.memory.margin_gib} GiB`",
            "",
            "## First Steps",
            "",
            "1. Put your local model path in `MODEL` or edit the scripts.",
            "2. Run `./preflight.sh` before launching any backend.",
            "3. Start with a short prompt and monitor memory pressure.",
            "",
            "```bash",
            f"MODEL={shlex.quote(model_path)} ./preflight.sh",
            "```",
            "",
            "## Generated Paths",
            "",
            "- `run-llama-cpp.sh`: llama.cpp smoke command",
            "- `run-mlx.sh`: MLX smoke command",
            "- `Modelfile` and `run-ollama.sh`: Ollama dry-run path",
            "- `local-llm-lab-plan.json`: full machine-readable plan",
            "",
            "## Warnings",
            "",
            warnings,
            "",
            "## Downgrade Options",
            "",
            downgrades,
            "",
        ]
    )


def generate_deploy_files(plan: PlanResult, out_dir: str | Path, *, model_path: str = "./model.gguf", dry_run: bool = True) -> DeployResult:
    target = Path(out_dir)
    target.mkdir(parents=True, exist_ok=True)
    files: list[str] = []
    warnings = list(plan.warnings)
    if not dry_run:
        warnings.append("v0.1 does not download giant models; generated commands still expect local model files.")

    config = {
        "dry_run": dry_run,
        "model": plan.inputs.model.to_dict(),
        "hardware": plan.inputs.hardware.to_dict(),
        "plan": plan.to_dict(),
        "model_path": model_path,
    }
    config_path = target / "local-llm-lab-plan.json"
    config_path.write_text(json.dumps(config, indent=2, sort_keys=True), encoding="utf-8")
    files.append(str(config_path))

    runbook = target / "README.md"
    runbook.write_text(_runbook(plan, model_path), encoding="utf-8")
    files.append(str(runbook))

    preflight = target / "preflight.sh"
    _write_executable(preflight, _preflight_script(plan, model_path))
    files.append(str(preflight))

    llama = target / "run-llama-cpp.sh"
    _write_executable(
        llama,
        "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "# Dry-run command generated by local-llm-lab. Edit MODEL before running.",
                f"MODEL=${{MODEL:-{model_path}}}",
                f"CTX=${{CTX:-{plan.inputs.context_tokens}}}",
                f"THREADS=${{THREADS:-{os.cpu_count() or 4}}}",
                "GPU_LAYERS=${GPU_LAYERS:--1}",
                'echo "llama.cpp plan: $MODEL ctx=$CTX gpu_layers=$GPU_LAYERS"',
                'llama-cli -m "$MODEL" --ctx-size "$CTX" --n-gpu-layers "$GPU_LAYERS" --threads "$THREADS" -p "Hello from local-llm-lab"',
                "",
            ]
        ),
    )
    files.append(str(llama))

    mlx = target / "run-mlx.sh"
    _write_executable(
        mlx,
        "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "# Dry-run command generated by local-llm-lab. MODEL can be a local path or HF repo.",
                f"MODEL=${{MODEL:-{plan.inputs.model.id}}}",
                f"MAX_TOKENS=${{MAX_TOKENS:-256}}",
                'echo "MLX plan: $MODEL max_tokens=$MAX_TOKENS"',
                'python -m mlx_lm.generate --model "$MODEL" --prompt "Hello from local-llm-lab" --max-tokens "$MAX_TOKENS"',
                "",
            ]
        ),
    )
    files.append(str(mlx))

    modelfile = target / "Modelfile"
    modelfile.write_text(
        "\n".join(
            [
                "# Dry-run Ollama Modelfile generated by local-llm-lab.",
                f"FROM {model_path}",
                f"PARAMETER num_ctx {plan.inputs.context_tokens}",
                "PARAMETER temperature 0.7",
                "PARAMETER top_p 0.9",
                "",
            ]
        ),
        encoding="utf-8",
    )
    files.append(str(modelfile))

    ollama = target / "run-ollama.sh"
    _write_executable(
        ollama,
        "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "NAME=${NAME:-local-llm-lab-model}",
                'echo "Creating Ollama model $NAME from generated Modelfile"',
                'ollama create "$NAME" -f Modelfile',
                'ollama run "$NAME" "Hello from local-llm-lab"',
                "",
            ]
        ),
    )
    files.append(str(ollama))
    return DeployResult(str(target), files, dry_run, warnings)
