from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path

from .planner import PlanResult


@dataclass
class DeployResult:
    out_dir: str
    files: list[str]
    dry_run: bool
    warnings: list[str]

    def to_dict(self) -> dict[str, object]:
        return {"out_dir": self.out_dir, "files": self.files, "dry_run": self.dry_run, "warnings": self.warnings}


def _write_executable(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8")
    path.chmod(path.stat().st_mode | 0o111)


def generate_deploy_files(plan: PlanResult, out_dir: str | Path, *, model_path: str = "./model.gguf", dry_run: bool = True) -> DeployResult:
    target = Path(out_dir)
    target.mkdir(parents=True, exist_ok=True)
    files: list[str] = []
    warnings = list(plan.warnings)
    if not dry_run:
        warnings.append("v0.1 does not download giant models; generated commands still expect local model files.")

    config = {
        "dry_run": dry_run,
        "model": plan.inputs.model.to_dict(),
        "hardware": plan.inputs.hardware.to_dict(),
        "plan": plan.to_dict(),
        "model_path": model_path,
    }
    config_path = target / "local-llm-lab-plan.json"
    config_path.write_text(json.dumps(config, indent=2, sort_keys=True), encoding="utf-8")
    files.append(str(config_path))

    llama = target / "run-llama-cpp.sh"
    _write_executable(
        llama,
        "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "# Dry-run command generated by local-llm-lab. Edit MODEL before running.",
                f"MODEL=${{MODEL:-{model_path}}}",
                f"CTX=${{CTX:-{plan.inputs.context_tokens}}}",
                f"THREADS=${{THREADS:-{os.cpu_count() or 4}}}",
                "GPU_LAYERS=${GPU_LAYERS:--1}",
                'echo "llama.cpp plan: $MODEL ctx=$CTX gpu_layers=$GPU_LAYERS"',
                'llama-cli -m "$MODEL" --ctx-size "$CTX" --n-gpu-layers "$GPU_LAYERS" --threads "$THREADS" -p "Hello from local-llm-lab"',
                "",
            ]
        ),
    )
    files.append(str(llama))

    mlx = target / "run-mlx.sh"
    _write_executable(
        mlx,
        "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "# Dry-run command generated by local-llm-lab. MODEL can be a local path or HF repo.",
                f"MODEL=${{MODEL:-{plan.inputs.model.id}}}",
                f"MAX_TOKENS=${{MAX_TOKENS:-256}}",
                'echo "MLX plan: $MODEL max_tokens=$MAX_TOKENS"',
                'python -m mlx_lm.generate --model "$MODEL" --prompt "Hello from local-llm-lab" --max-tokens "$MAX_TOKENS"',
                "",
            ]
        ),
    )
    files.append(str(mlx))

    modelfile = target / "Modelfile"
    modelfile.write_text(
        "\n".join(
            [
                "# Dry-run Ollama Modelfile generated by local-llm-lab.",
                f"FROM {model_path}",
                f"PARAMETER num_ctx {plan.inputs.context_tokens}",
                "PARAMETER temperature 0.7",
                "PARAMETER top_p 0.9",
                "",
            ]
        ),
        encoding="utf-8",
    )
    files.append(str(modelfile))

    ollama = target / "run-ollama.sh"
    _write_executable(
        ollama,
        "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "NAME=${NAME:-local-llm-lab-model}",
                'echo "Creating Ollama model $NAME from generated Modelfile"',
                'ollama create "$NAME" -f Modelfile',
                'ollama run "$NAME" "Hello from local-llm-lab"',
                "",
            ]
        ),
    )
    files.append(str(ollama))
    return DeployResult(str(target), files, dry_run, warnings)

